# Generated by Django 5.2.9 on 2025-12-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='image')),
                ('video', models.FileField(upload_to='video')),
                ('audio', models.FileField(upload_to='audio')),
                ('file', models.FileField(upload_to='video')),
            ],
        ),
    ]
